# Generated by Django 4.1.7 on 2023-04-19 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_tag_description_remove_tag_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$', message='Incorrect expression of e-mail.')]),
        ),
    ]
