# Generated by Django 4.1.7 on 2023-04-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_author_email_alter_newsletter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/default.png', null=True, upload_to='users'),
        ),
    ]
