# Generated by Django 4.1.7 on 2023-04-27 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Information about user', null=True, validators=[django.core.validators.MinLengthValidator(30, django.core.validators.MaxLengthValidator(2000))]),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(default='Information about author', validators=[django.core.validators.MinLengthValidator(30, django.core.validators.MaxLengthValidator(2000))]),
        ),
    ]
