# Generated by Django 4.1.7 on 2023-04-27 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_user_description_user_slug_alter_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='Information about user', null=True, validators=[django.core.validators.MinLengthValidator(30), django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
