# Generated by Django 4.1.7 on 2023-05-06 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_alter_author_description_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(default='Information about author.', validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='users/default.png', null=True, upload_to='authors'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='Information about user.', null=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
